language: ruby
sudo: false
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
notifications:
  recipients:
    - memde@engineyard.com
    - srosenfeld@engineyard.com
    - jallen@engineyard.com
  webhooks:
    urls:
      - https://ensemble.engineyard.com/travis
    on_success: always
    on_failure: always
    on_start: true
